# Generated by Django 4.2.7 on 2023-11-30 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
        ('message', '0002_rename_client_id_message_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='newsletter_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='newsletter.newsletter'),
        ),
    ]
