# Generated by Django 4.2.7 on 2023-11-27 16:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '7хххххххххх'. Need 12 digits.", regex='^7[0-9]{10}$')]),
        ),
    ]
