# Generated by Django 4.2.7 on 2023-12-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_mobile_operator_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tag',
            field=models.CharField(db_index=True),
        ),
    ]
