version: "3.10"

services:
  db:
    image: postgres:14
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./notification_service/.env
  backend:
    container_name: notification_service_backend
    build: ./notification_service
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - ./notification_service:/app/backend
    ports:
      - "8000:8000"
    env_file:
      - notification_service/.env
    depends_on:
      - db
  redis:
    container_name: redis
    hostname: redis
    image: redis:latest
    ports:
      - "6379:6379"
    restart: on-failure
  celery:
    build: ./notification_service
    command: celery -A notification_service worker --beat
    restart: always
    volumes:
      - ./notification_service:/app/backend
    depends_on:
      - redis
      - backend
volumes:
  postgres_data: