# Generated by Django 4.2.7 on 2023-11-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='client_filter',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
